# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/glenn/reliable

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/glenn/reliable

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/glenn/reliable/CMakeFiles /Users/glenn/reliable//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/glenn/reliable/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named reliable

# Build rule for target.
reliable: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reliable
.PHONY : reliable

# fast build rule for target.
reliable/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reliable.dir/build.make CMakeFiles/reliable.dir/build
.PHONY : reliable/fast

#=============================================================================
# Target rules for targets named reliable_test

# Build rule for target.
reliable_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 reliable_test
.PHONY : reliable_test

# fast build rule for target.
reliable_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reliable_test.dir/build.make CMakeFiles/reliable_test.dir/build
.PHONY : reliable_test/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named soak

# Build rule for target.
soak: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 soak
.PHONY : soak

# fast build rule for target.
soak/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soak.dir/build.make CMakeFiles/soak.dir/build
.PHONY : soak/fast

#=============================================================================
# Target rules for targets named stats

# Build rule for target.
stats: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stats
.PHONY : stats

# fast build rule for target.
stats/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/build
.PHONY : stats/fast

#=============================================================================
# Target rules for targets named fuzz

# Build rule for target.
fuzz: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fuzz
.PHONY : fuzz

# fast build rule for target.
fuzz/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fuzz.dir/build.make CMakeFiles/fuzz.dir/build
.PHONY : fuzz/fast

example.o: example.c.o
.PHONY : example.o

# target to build an object file
example.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.c.o
.PHONY : example.c.o

example.i: example.c.i
.PHONY : example.i

# target to preprocess a source file
example.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.c.i
.PHONY : example.c.i

example.s: example.c.s
.PHONY : example.s

# target to generate assembly for a file
example.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/example.dir/build.make CMakeFiles/example.dir/example.c.s
.PHONY : example.c.s

fuzz.o: fuzz.c.o
.PHONY : fuzz.o

# target to build an object file
fuzz.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fuzz.dir/build.make CMakeFiles/fuzz.dir/fuzz.c.o
.PHONY : fuzz.c.o

fuzz.i: fuzz.c.i
.PHONY : fuzz.i

# target to preprocess a source file
fuzz.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fuzz.dir/build.make CMakeFiles/fuzz.dir/fuzz.c.i
.PHONY : fuzz.c.i

fuzz.s: fuzz.c.s
.PHONY : fuzz.s

# target to generate assembly for a file
fuzz.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fuzz.dir/build.make CMakeFiles/fuzz.dir/fuzz.c.s
.PHONY : fuzz.c.s

reliable.o: reliable.c.o
.PHONY : reliable.o

# target to build an object file
reliable.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reliable.dir/build.make CMakeFiles/reliable.dir/reliable.c.o
.PHONY : reliable.c.o

reliable.i: reliable.c.i
.PHONY : reliable.i

# target to preprocess a source file
reliable.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reliable.dir/build.make CMakeFiles/reliable.dir/reliable.c.i
.PHONY : reliable.c.i

reliable.s: reliable.c.s
.PHONY : reliable.s

# target to generate assembly for a file
reliable.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reliable.dir/build.make CMakeFiles/reliable.dir/reliable.c.s
.PHONY : reliable.c.s

soak.o: soak.c.o
.PHONY : soak.o

# target to build an object file
soak.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soak.dir/build.make CMakeFiles/soak.dir/soak.c.o
.PHONY : soak.c.o

soak.i: soak.c.i
.PHONY : soak.i

# target to preprocess a source file
soak.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soak.dir/build.make CMakeFiles/soak.dir/soak.c.i
.PHONY : soak.c.i

soak.s: soak.c.s
.PHONY : soak.s

# target to generate assembly for a file
soak.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/soak.dir/build.make CMakeFiles/soak.dir/soak.c.s
.PHONY : soak.c.s

stats.o: stats.c.o
.PHONY : stats.o

# target to build an object file
stats.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats.c.o
.PHONY : stats.c.o

stats.i: stats.c.i
.PHONY : stats.i

# target to preprocess a source file
stats.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats.c.i
.PHONY : stats.c.i

stats.s: stats.c.s
.PHONY : stats.s

# target to generate assembly for a file
stats.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stats.dir/build.make CMakeFiles/stats.dir/stats.c.s
.PHONY : stats.c.s

test.o: test.cpp.o
.PHONY : test.o

# target to build an object file
test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reliable_test.dir/build.make CMakeFiles/reliable_test.dir/test.cpp.o
.PHONY : test.cpp.o

test.i: test.cpp.i
.PHONY : test.i

# target to preprocess a source file
test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reliable_test.dir/build.make CMakeFiles/reliable_test.dir/test.cpp.i
.PHONY : test.cpp.i

test.s: test.cpp.s
.PHONY : test.s

# target to generate assembly for a file
test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/reliable_test.dir/build.make CMakeFiles/reliable_test.dir/test.cpp.s
.PHONY : test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... example"
	@echo "... fuzz"
	@echo "... reliable"
	@echo "... reliable_test"
	@echo "... soak"
	@echo "... stats"
	@echo "... example.o"
	@echo "... example.i"
	@echo "... example.s"
	@echo "... fuzz.o"
	@echo "... fuzz.i"
	@echo "... fuzz.s"
	@echo "... reliable.o"
	@echo "... reliable.i"
	@echo "... reliable.s"
	@echo "... soak.o"
	@echo "... soak.i"
	@echo "... soak.s"
	@echo "... stats.o"
	@echo "... stats.i"
	@echo "... stats.s"
	@echo "... test.o"
	@echo "... test.i"
	@echo "... test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

